Feature/celery
khalifakarim/test_project pull request #3
Opened 2021-08-02 19:33 UTC by khalifakarim

2021-08-03 08:14 UTC, isoldatenko requested changes

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/exceptions/balance.py
> +        self.showroom_name = showroom_name
`BalanceError` должна быть универсальной, а не относится только к автосалону

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/exceptions/sale_history.py
> +        return f"{self.showroom_name} has no sales history"
Должна быть универсальной, а не только относится к автосалону, потому что такая же ошибка может возникнуть относительно поставщика

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/serializers/car_dealership.py
> +    def validate_preferred_characteristics(self, preferred_characteristics):
Добавь вылидацию того, что все ключи словаря `preffred_characteristics` действительно существует в таблице `Car` в качестве колонок

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/create_available_cars.py
> +    return iter_cars(cars, showroom)
`return` - лишний, `tier_cars` - ничего не возвращает

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/create_available_cars.py
> +def iter_cars(cars, showroom):
Лучше назвать `create_available_cars` или `create_carshowroom_cars`

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    CarDealershipBuy,
по убыванию

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/create_available_cars.py
> +                car=car.pk,
Достаточно передать просто объект, а не `pk`

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    cars = CarDealershipSale.objects.filter(car_dealership=showroom.id).aggregate(Count('car__id')).order_by(
`.filter(car_dealership=showroom)` - достаточно

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    for car in cars:
пустуюю строку

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    return _check_balance(showroom, providers)
пустую строку

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +            car=car.pk, ).order_by('price')
Исправь код стайл

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    showroom.save()
`.update()` используй

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +                                    cars_quantity=1)
Исправь код стайл

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +                                    cars_quantity=1)
Нужно просто передавать связанные объекты, а не их `.id`

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +from car_dealerships.api.v1.services.create_available_cars import create_available_cars
по убыванию

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/client/api/v1/serializers/offer.py
> +        total_price = active_offers.aggregate(total_price=Sum('max_price'))['total_price'] or 0
Пустую строку

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/pyhtonProject33/settings.py
> +
Лишняя пустая строка

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/pyhtonProject33/settings.py
> +CELERY_BROKER_URL = 'redis://redis:6379'
Переменную окружения используй

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/client/api/v1/services/offer_logic.py
> +    offer.save()
Используй `.update()`

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/client/api/v1/services/offer_logic.py
> +    car.save()
используй `.update()`

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/client/api/v1/services/offer_logic.py
> +    user.save()
Используй `.update()`

2021-08-03 08:14 UTC, isoldatenko commented on pythonProject33/client/api/v1/services/offer_logic.py
> +    _showroom_additions_balance(car)
пустую строку

2021-08-03 11:24 UTC, isoldatenko requested changes

2021-08-03 11:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/serializers/car_dealership.py
> +            raise serializers.ValidationError
`raise serialisers.ValidationError("<message>")` - добавь `message`

2021-08-03 11:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/create_available_cars.py
> +    available_cars = []
пустую строку после локального импорта

2021-08-03 15:13 UTC, isoldatenko commented
xyeta polnaya

2021-08-04 08:24 UTC, isoldatenko requested changes

2021-08-04 08:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/serializers/car_dealership.py
> +        return preferred_characteristics
пустую строку

2021-08-04 08:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/serializers/car_dealership.py
> +            raise serializers.ValidationError("incorrect data")
В `ValidationError` прокидывай словарь в формате `{'<field_name>': '<message>'}`

2021-08-04 08:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/serializers/car_dealership.py
> +        if not set(preferred_characteristics.keys()).issubset(set(car_characteristics)):
Преобразовывать `car_characteristics` в `set` не нужно

2021-08-04 08:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +        return super().get_queryset().filter(is_active=True)
Создай родительский менеджер, так как везде одна и та же логика используется

2021-08-04 08:24 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    return _check_balance(showroom, providers)
Исправить логику, исходя из того, что поставщики конкретной машины для конкретного автосалона заранее известны

2021-08-04 19:49 UTC, isoldatenko requested changes

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/provider/admin.py
> +        "car",
зачем тут поменял?

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/client/models.py
> +        return super().get_active_instance()
просто используй `.get_active_instances` там где тебе нужны какие - либо активные объекты, этот метод по факту лишний

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/client/models.py
> +        return super().get_queryset().filter(is_active=True, user__id=user_id)
можно использовать `super().get_active_instances().filter(user__id=user_id)`

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/tasks.py
> +        except SaleHistoryError:
логгирование ошибки должно быть

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/tasks.py
> +from car_dealerships.api.v1.services.popular_car_logic import (
пустую строку

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +        return super().get_active_instance()
Используй `get_active_instances()`, метод лишний по факту

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +    def get_active_instance(self):
Назови `get_active_instances()`

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +class SoftDeleteManager(models.Manager):
Вынеси в `core`

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +    car = models.ForeignKey('provider.Car', on_delete=models.CASCADE)
`related_name='+'` добавь

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +            raise BalanceError(showroom.name)
Эта ошибка тоже должна отлавливаться в одном из методов как и `SaleHistoryError`

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +        super(CarDealership, self).save(*args, **kwargs)
Достаточно просто `super()`

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +from car_dealerships.api.v1.services.create_available_cars import create_available_cars
Модули не должны называть глаголами

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +    return _check_balance(showroom, purchase_characteristics)
нужен ли тут `return`?

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/create_purchase_characteristics.py
> +        providers.extend(CarPrice.objects.filter(car=car.car).order_by('price'))
фильтровать нужно по `-price`

2021-08-04 19:49 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/create_purchase_characteristics.py
> +        providers.extend(CarPrice.objects.filter(car=car.car).order_by('price'))
Скорее всего также нужна фильтрация по переданному автосалону

2021-08-05 08:45 UTC, GlebZhnkvch commented on pythonProject33/.env
> -USE_SWAGGER=1
добавь пустую строку

2021-08-05 08:45 UTC, GlebZhnkvch commented on pythonProject33/.env
> +CELERY_RESULT_SERIALIZER=json
добавь пустую строку

2021-08-05 10:39 UTC, isoldatenko requested changes

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/car_dealerships/api/v1/services/popular_car_logic.py
> +import logging
`import logging` должен быть первыми и после него пустая строка

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +    objects = CarDealershipManager()
Используй `SoftDeleteManager`

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/car_dealerships/models.py
> +
Лишний класс

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/client/models.py
> +    car_dealership = models.ForeignKey(CarDealership, on_delete=models.CASCADE, related_name='regular_customers')
Добавить `FK` на `customer`

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/client/models.py
> +class RegularClient(models.Model):
Используй в качестве промежуточной таблицы между автосалоном и клиентом

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/client/api/v1/services/offer_logic.py
> +        cars_quantity__gt=0).order_by('price').first()
Цена должна быть больше нуля, иначе это будет значить, что цена на машину в автосалоне не выставлена

2021-08-05 10:39 UTC, isoldatenko commented on pythonProject33/car_dealerships/tasks.py
> +import logging
в самое начало импортов

2021-08-05 10:51 UTC, isoldatenko approved these changes

2021-08-05 10:53 UTC, merged